INSERT INTO `Capstone`.`Category` values(1,'Regular Coaster','Regular sized coaster',' http://www.thomassoliday.com/photos/category1.jpg');
INSERT INTO `Capstone`.`Category` values(2,'Car Coasters','small coasters for the car','http://www.thomassoliday.com/photos/category1.jpg');
INSERT INTO `Capstone`.`Category` values(3,'Large Car Coasters','large coasters for the car','http://www.thomassoliday.com/photos/category1.jpg');
INSERT INTO `Capstone`.`Category` values(4,'Botanical Coasters','coasters with real leaves','http://www.thomassoliday.com/photos/category1.jpg');


INSERT INTO `Capstone`.`Products` values(1,'Flamingo','Regular sized coaster ',1,9.95,10,'/photos/coaster1.jpg');
INSERT INTO `Capstone`.`Products` values(2,'KoKo','Regular sized coaster ',1,9.95,10,'/photos/coaster2.jpg');
INSERT INTO `Capstone`.`Products` values(3,'Palm Tree','Regular sized coaster ',1,9.95,10,'/photos/coaster3.jpg');
INSERT INTO `Capstone`.`Products` values(4,'Holly','Regular sized coaster ',1,9.95,10,'/photos/coaster4.jpg');
INSERT INTO `Capstone`.`Products` values(5,'Fish','Regular sized coaster ',1,9.95,10,'/photos/coaster5.jpg');
INSERT INTO `Capstone`.`Products` values(6,'Deer Scene','Regular sized coaster ',1,9.95,10,'/photos/coaster6.jpg');
INSERT INTO `Capstone`.`Products` values(7,'Dolphin Shell Ring','Regular sized coaster ',1,9.95,10,'/photos/coaster7.jpg');
INSERT INTO `Capstone`.`Products` values(8,'Sailboat','Regular sized coaster ',1,9.95,10,'/photos/coaster8.jpg');
INSERT INTO `Capstone`.`Products` values(9,'Shell Ring','Regular sized coaster ',1,9.95,10,'/photos/coaster9.jpg');
INSERT INTO `Capstone`.`Products` values(10,'Blue Jay','Regular sized coaster ',1,9.95,10,'/photos/coaster10.jpg');
INSERT INTO `Capstone`.`Products` values(11,'Manatee Multi Color','Regular sized coaster ',1,9.95,10,'/photos/coaster11.jpg');
INSERT INTO `Capstone`.`Products` values(12,'Bear','Regular sized coaster ',1,9.95,10,'/photos/coaster12.jpg');
INSERT INTO `Capstone`.`Products` values(13,'Bird Red','Regular sized coaster ',1,9.95,10,'/photos/coaster13.jpg');
INSERT INTO `Capstone`.`Products` values(14,'Bird Blue','Regular sized coaster ',1,9.95,10,'/photos/coaster14.jpg');
INSERT INTO `Capstone`.`Products` values(15,'Grapes','Regular sized coaster ',1,9.95,10,'/photos/coaster15.jpg');
INSERT INTO `Capstone`.`Products` values(16,'Frog Dragonfly Blue','Regular sized coaster ',1,9.95,10,'/photos/coaster16.jpg');
INSERT INTO `Capstone`.`Products` values(17,'Frog Dragonfly Red','Regular sized coaster ',1,9.95,10,'/photos/coaster17.jpg');
INSERT INTO `Capstone`.`Products` values(18,'Brown Shell Scene','Regular sized coaster ',1,9.95,10,'/photos/coaster18.jpg');
INSERT INTO `Capstone`.`Products` values(19,'Brown Shell Scene 1','Regular sized coaster ',1,9.95,10,'/photos/coaster19.jpg');
INSERT INTO `Capstone`.`Products` values(20,'Palm Tree','Regular sized coaster ',1,9.95,10,'/photos/coaster20.jpg');
INSERT INTO `Capstone`.`Products` values(21,'shell scene brown','Regular sized coaster ',1,9.95,10,'/photos/coaster21.jpg');
INSERT INTO `Capstone`.`Products` values(22,'blue crab','Regular sized coaster ',1,9.95,10,'/photos/coaster22.jpg');
INSERT INTO `Capstone`.`Products` values(23,'sand dollar','Regular sized coaster ',1,9.95,10,'/photos/coaster23.jpg');
INSERT INTO `Capstone`.`Products` values(24,'multi color sea turtle','Regular sized coaster ',1,9.95,10,'/photos/coaster24.jpg');
INSERT INTO `Capstone`.`Products` values(25,'Lady Bug','Regular sized coaster ',1,9.95,10,'/photos/coaster25.jpg');
INSERT INTO `Capstone`.`Products` values(26,'frog dragonfly yellow','Regular sized coaster ',1,9.95,10,'/photos/coaster26.jpg');
INSERT INTO `Capstone`.`Products` values(27,'frog dragonfly red/purple','Regular sized coaster ',1,9.95,10,'/photos/coaster27.jpg');
INSERT INTO `Capstone`.`Products` values(28,'horse','Regular sized coaster ',1,9.95,10,'/photos/coaster28.jpg');
INSERT INTO `Capstone`.`Products` values(29,'flower','Regular sized coaster ',1,9.95,10,'/photos/coaster29.jpg');
INSERT INTO `Capstone`.`Products` values(30,'3 fish','Regular sized coaster ',1,9.95,10,'/photos/coaster30.jpg');
INSERT INTO `Capstone`.`Products` values(31,'snowman','Regular sized coaster ',1,9.95,10,'/photos/coaster31.jpg');
INSERT INTO `Capstone`.`Products` values(32,'TUIT','Regular sized coaster ',1,9.95,10,'/photos/coaster32.jpg');
INSERT INTO `Capstone`.`Products` values(33,'13 Star Flag','Regular sized coaster ',1,9.95,10,'/photos/coaster33.jpg');
INSERT INTO `Capstone`.`Products` values(34,'Red crab','Regular sized coaster ',1,9.95,10,'/photos/coaster34.jpg');
INSERT INTO `Capstone`.`Products` values(35,'red and blue crab shell ring','Regular sized coaster ',1,9.95,10,'/photos/coaster35.jpg');
INSERT INTO `Capstone`.`Products` values(36,'red and blue crab','Regular sized coaster ',1,9.95,10,'/photos/coaster36.jpg');
INSERT INTO `Capstone`.`Products` values(37,'Flip Flops','Regular sized coaster ',1,9.95,10,'/photos/coaster37.jpg');
INSERT INTO `Capstone`.`Products` values(38,'flip flops','Regular sized coaster ',1,9.95,10,'/photos/coaster38.jpg');
INSERT INTO `Capstone`.`Products` values(39,'flipflops','Regular sized coaster ',1,9.95,10,'/photos/coaster39.jpg');
INSERT INTO `Capstone`.`Products` values(40,'butterfly blue','Regular sized coaster ',1,9.95,10,'/photos/coaster40.jpg');
INSERT INTO `Capstone`.`Products` values(41,'butterfly yellow','Regular sized coaster ',1,9.95,10,'/photos/coaster41.jpg');
INSERT INTO `Capstone`.`Products` values(42,'butterfly red blue','Regular sized coaster ',1,9.95,10,'/photos/coaster42.jpg');
INSERT INTO `Capstone`.`Products` values(46,'shell spread','Car Coasters',2,9.95,10,'/photos/car1.jpg');
INSERT INTO `Capstone`.`Products` values(47,'Crab - Red','Car Coasters',2,9.95,10,'/photos/car2.jpg');
INSERT INTO `Capstone`.`Products` values(48,'flamingo','Car Coasters',2,9.95,10,'/photos/car3.jpg');
INSERT INTO `Capstone`.`Products` values(49,'flower','Car Coasters',2,9.95,10,'/photos/car4.jpg');
INSERT INTO `Capstone`.`Products` values(50,'palm tree','Car Coasters',2,9.95,10,'/photos/car5.jpg');
INSERT INTO `Capstone`.`Products` values(51,'dolphin blue','Car Coasters',2,9.95,10,'/photos/car6.jpg');
INSERT INTO `Capstone`.`Products` values(52,'Lady Bug','Car Coasters',2,9.95,10,'/photos/car7.jpg');
INSERT INTO `Capstone`.`Products` values(53,'flower','Car Coasters',2,9.95,10,'/photos/car8.jpg');
INSERT INTO `Capstone`.`Products` values(54,'turtle','Car Coasters',2,9.95,10,'/photos/car9.jpg');
INSERT INTO `Capstone`.`Products` values(55,'dolphin','Car Coasters',2,9.95,10,'/photos/car10.jpg');
INSERT INTO `Capstone`.`Products` values(56,'Flower - red','Car Coasters',2,9.95,10,'/photos/car11.jpg');
INSERT INTO `Capstone`.`Products` values(57,'crab blue','Car Coasters',2,9.95,10,'/photos/car12.jpg');
INSERT INTO `Capstone`.`Products` values(58,'pelican','Car Coasters',2,9.95,10,'/photos/car13.jpg');
INSERT INTO `Capstone`.`Products` values(59,'4 flowers','Car Coasters',2,9.95,10,'/photos/car14.jpg');
INSERT INTO `Capstone`.`Products` values(60,'flower yellow','Car Coasters',2,9.95,10,'/photos/car15.jpg');
INSERT INTO `Capstone`.`Products` values(61,'Flower - Wineberry','Car Coasters',2,9.95,10,'/photos/car16.jpg');
INSERT INTO `Capstone`.`Products` values(62,'Flower - blue','Car Coasters',2,9.95,10,'/photos/car17.jpg');
INSERT INTO `Capstone`.`Products` values(63,'flower - red','Car Coasters',2,9.95,10,'/photos/car18.jpg');
INSERT INTO `Capstone`.`Products` values(64,'deer ','Car Coasters',2,9.95,10,'/photos/car19.jpg');
INSERT INTO `Capstone`.`Products` values(65,'flower pink','Car Coasters',2,9.95,10,'/photos/car20.jpg');
INSERT INTO `Capstone`.`Products` values(66,'flower blue','Car Coasters',2,9.95,10,'/photos/car21.jpg');
INSERT INTO `Capstone`.`Products` values(67,'flower red','Car Coasters',2,9.95,10,'/photos/car22.jpg');
INSERT INTO `Capstone`.`Products` values(68,'flower blue','Car Coasters',2,9.95,10,'/photos/car23.jpg');
INSERT INTO `Capstone`.`Products` values(69,'flower purple','Car Coasters',2,9.95,10,'/photos/car24.jpg');
INSERT INTO `Capstone`.`Products` values(70,'cardinal','Car Coasters',2,9.95,10,'/photos/car25.jpg');
INSERT INTO `Capstone`.`Products` values(71,'lizards','Car Coasters',2,9.95,10,'/photos/car26.jpg');
INSERT INTO `Capstone`.`Products` values(72,'crab blue','Car Coasters',2,9.95,10,'/photos/car27.jpg');
INSERT INTO `Capstone`.`Products` values(73,'pelican','Car Coasters',2,9.95,10,'/photos/car28.jpg');
INSERT INTO `Capstone`.`Products` values(74,'shell flower','Car Coasters',2,9.95,10,'/photos/car29.jpg');
INSERT INTO `Capstone`.`Products` values(75,'horse','Car Coasters',2,9.95,10,'/photos/car30.jpg');
INSERT INTO `Capstone`.`Products` values(76,'shell spread','Car Coasters',2,9.95,10,'/photos/car31.jpg');
INSERT INTO `Capstone`.`Products` values(77,'fish shells','Car Coasters',2,9.95,10,'/photos/car32.jpg');
INSERT INTO `Capstone`.`Products` values(78,'fish shell 2','Car Coasters',2,9.95,10,'/photos/car33.jpg');
INSERT INTO `Capstone`.`Products` values(79,'lighthouse','Car Coasters',2,9.95,10,'/photos/car34.jpg');
INSERT INTO `Capstone`.`Products` values(80,'flamingo','Car Coasters',2,9.95,10,'/photos/car35.jpg');
INSERT INTO `Capstone`.`Products` values(81,'pinapple','Car Coasters',2,9.95,10,'/photos/car36.jpg');
INSERT INTO `Capstone`.`Products` values(82,'pinapple','Car Coasters',2,9.95,10,'/photos/car37.jpg');
INSERT INTO `Capstone`.`Products` values(83,'Butterfly','Large Car Coasters',3,9.95,10,'/photos/car38.jpg');
INSERT INTO `Capstone`.`Products` values(84,'Crab - Blue','Large Car Coasters',3,9.95,10,'/photos/car39.jpg');
INSERT INTO `Capstone`.`Products` values(85,'Crab - Red','Large Car Coasters',3,9.95,10,'/photos/car40.jpg');
INSERT INTO `Capstone`.`Products` values(86,'Deer','Large Car Coasters',3,9.95,10,'/photos/car41.jpg');
INSERT INTO `Capstone`.`Products` values(87,'Dolphin','Large Car Coasters',3,9.95,10,'/photos/car42.jpg');
INSERT INTO `Capstone`.`Products` values(88,'Dragon Fly','Large Car Coasters',3,9.95,10,'/photos/car43.jpg');
INSERT INTO `Capstone`.`Products` values(89,'DragonFly w/Cattail','Large Car Coasters',3,9.95,10,'/photos/car44.jpg');
INSERT INTO `Capstone`.`Products` values(90,'Fish (3 fish)','Large Car Coasters',3,9.95,10,'/photos/car45.jpg');
INSERT INTO `Capstone`.`Products` values(91,'Flamingo','Large Car Coasters',3,9.95,10,'/photos/car46.jpg');
INSERT INTO `Capstone`.`Products` values(92,'Flip Flops (3 pair)','Large Car Coasters',3,9.95,10,'/photos/car47.jpg');
INSERT INTO `Capstone`.`Products` values(93,'Freeform Shell','Large Car Coasters',3,9.95,10,'/photos/car48.jpg');
INSERT INTO `Capstone`.`Products` values(94,'Freeform Shell - Flower','Large Car Coasters',3,9.95,10,'/photos/car49.jpg');
INSERT INTO `Capstone`.`Products` values(95,'Flower - Blue','Large Car Coasters',3,9.95,10,'/photos/car50.jpg');
INSERT INTO `Capstone`.`Products` values(96,'Flower - Peach','Large Car Coasters',3,9.95,10,'/photos/car51.jpg');
INSERT INTO `Capstone`.`Products` values(97,'Flower - Pink','Large Car Coasters',3,9.95,10,'/photos/car52.jpg');
INSERT INTO `Capstone`.`Products` values(98,'Flower - Purple','Large Car Coasters',3,9.95,10,'/photos/car53.jpg');
INSERT INTO `Capstone`.`Products` values(99,'Flower - Red','Large Car Coasters',3,9.95,10,'/photos/car54.jpg');
INSERT INTO `Capstone`.`Products` values(100,'Flower - Wineberry','Large Car Coasters',3,9.95,10,'/photos/car55.jpg');
INSERT INTO `Capstone`.`Products` values(101,'Flower - Yellow','Large Car Coasters',3,9.95,10,'/photos/car56.jpg');
INSERT INTO `Capstone`.`Products` values(102,'Frogs','Large Car Coasters',3,9.95,10,'/photos/car57.jpg');
INSERT INTO `Capstone`.`Products` values(103,'Hands','Large Car Coasters',3,9.95,10,'/photos/car58.jpg');
INSERT INTO `Capstone`.`Products` values(104,'Horse','Large Car Coasters',3,9.95,10,'/photos/car59.jpg');
INSERT INTO `Capstone`.`Products` values(105,'Kokopeli','Large Car Coasters',3,9.95,10,'/photos/car60.jpg');
INSERT INTO `Capstone`.`Products` values(106,'Lady Bug','Large Car Coasters',3,9.95,10,'/photos/car61.jpg');
INSERT INTO `Capstone`.`Products` values(107,'Lighthouse - Blue','Large Car Coasters',3,9.95,10,'/photos/car62.jpg');
INSERT INTO `Capstone`.`Products` values(108,'Lighthouse - Purple','Large Car Coasters',3,9.95,10,'/photos/car63.jpg');
INSERT INTO `Capstone`.`Products` values(109,'Lighthouse - Red','Large Car Coasters',3,9.95,10,'/photos/car64.jpg');
INSERT INTO `Capstone`.`Products` values(110,'Lighthouse - Wineberry','Large Car Coasters',3,9.95,10,'/photos/car65.jpg');
INSERT INTO `Capstone`.`Products` values(111,'Lighthouse - Yellow','Large Car Coasters',3,9.95,10,'/photos/car66.jpg');
INSERT INTO `Capstone`.`Products` values(112,'Palm Tree','Large Car Coasters',3,9.95,10,'/photos/car67.jpg');
INSERT INTO `Capstone`.`Products` values(113,'Pelican','Large Car Coasters',3,9.95,10,'/photos/car68.jpg');
INSERT INTO `Capstone`.`Products` values(114,'Pinapple','Large Car Coasters',3,9.95,10,'/photos/car69.jpg');
INSERT INTO `Capstone`.`Products` values(115,'Sailboat','Large Car Coasters',3,9.95,10,'/photos/car70.jpg');
INSERT INTO `Capstone`.`Products` values(116,'Tuit','Large Car Coasters',3,9.95,10,'/photos/car71.jpg');
INSERT INTO `Capstone`.`Products` values(117,'Turtles','Large Car Coasters',3,9.95,10,'/photos/car72.jpg');
INSERT INTO `Capstone`.`Products` values(118,'Botanical Coaster 1','Botanical Coasters',4,19.95,1,'/photos/leaf1.jpg');
INSERT INTO `Capstone`.`Products` values(119,'Botanical Coaster 2','Botanical Coasters',4,19.95,1,'/photos/leaf2.jpg');
INSERT INTO `Capstone`.`Products` values(120,'Botanical Coaster 3','Botanical Coasters',4,19.95,1,'/photos/leaf3.jpg');
INSERT INTO `Capstone`.`Products` values(121,'Botanical Coaster 4','Botanical Coasters',4,19.95,1,'/photos/leaf4.jpg');
INSERT INTO `Capstone`.`Products` values(122,'Botanical Coaster 5','Botanical Coasters',4,19.95,1,'/photos/leaf5.jpg');
INSERT INTO `Capstone`.`Products` values(123,'Botanical Coaster 6','Botanical Coasters',4,19.95,1,'/photos/leaf6.jpg');
INSERT INTO `Capstone`.`Products` values(124,'Botanical Coaster 7','Botanical Coasters',4,19.95,1,'/photos/leaf7.jpg');
INSERT INTO `Capstone`.`Products` values(125,'Botanical Coaster 8','Botanical Coasters',4,19.95,1,'/photos/leaf8.jpg');
INSERT INTO `Capstone`.`Products` values(126,'Botanical Coaster 9','Botanical Coasters',4,19.95,1,'/photos/leaf9.jpg');
INSERT INTO `Capstone`.`Products` values(127,'Botanical Coaster 10','Botanical Coasters',4,19.95,1,'/photos/leaf10.jpg');
INSERT INTO `Capstone`.`Products` values(128,'Botanical Coaster 11','Botanical Coasters',4,19.95,1,'/photos/leaf11.jpg');
INSERT INTO `Capstone`.`Products` values(129,'Botanical Coaster 12','Botanical Coasters',4,19.95,1,'/photos/leaf12.jpg');
INSERT INTO `Capstone`.`Products` values(130,'Botanical Coaster 13','Botanical Coasters',4,19.95,1,'/photos/leaf13.jpg');
INSERT INTO `Capstone`.`Products` values(131,'Botanical Coaster 14','Botanical Coasters',4,19.95,1,'/photos/leaf14.jpg');
INSERT INTO `Capstone`.`Products` values(132,'Botanical Coaster 15','Botanical Coasters',4,19.95,1,'/photos/leaf15.jpg');
INSERT INTO `Capstone`.`Products` values(133,'Botanical Coaster 16','Botanical Coasters',4,19.95,1,'/photos/leaf16.jpg');
INSERT INTO `Capstone`.`Products` values(134,'Botanical Coaster 17','Botanical Coasters',4,19.95,1,'/photos/leaf17.jpg');
INSERT INTO `Capstone`.`Products` values(135,'Botanical Coaster 18','Botanical Coasters',4,19.95,1,'/photos/leaf18.jpg');
INSERT INTO `Capstone`.`Products` values(136,'Botanical Coaster 19','Botanical Coasters',4,19.95,1,'/photos/leaf19.jpg');
INSERT INTO `Capstone`.`Products` values(137,'Botanical Coaster 20','Botanical Coasters',4,19.95,1,'/photos/leaf20.jpg');
INSERT INTO `Capstone`.`Products` values(138,'Botanical Coaster 21','Botanical Coasters',4,19.95,1,'/photos/leaf21.jpg');
INSERT INTO `Capstone`.`Products` values(139,'Botanical Coaster 22','Botanical Coasters',4,19.95,1,'/photos/leaf22.jpg');
INSERT INTO `Capstone`.`Products` values(140,'Botanical Coaster 23','Botanical Coasters',4,19.95,1,'/photos/leaf23.jpg');
INSERT INTO `Capstone`.`Products` values(141,'Botanical Coaster 24','Botanical Coasters',4,19.95,1,'/photos/leaf24.jpg');
INSERT INTO `Capstone`.`Products` values(142,'Botanical Coaster 25','Botanical Coasters',4,19.95,1,'/photos/leaf25.jpg');
INSERT INTO `Capstone`.`Products` values(143,'Botanical Coaster 26','Botanical Coasters',4,19.95,1,'/photos/leaf26.jpg');
INSERT INTO `Capstone`.`Products` values(144,'Botanical Coaster 27','Botanical Coasters',4,19.95,1,'/photos/leaf27.jpg');
INSERT INTO `Capstone`.`Products` values(145,'Botanical Coaster 28','Botanical Coasters',4,19.95,1,'/photos/leaf28.jpg');
INSERT INTO `Capstone`.`Products` values(146,'Botanical Coaster 29','Botanical Coasters',4,19.95,1,'/photos/leaf29.jpg');
INSERT INTO `Capstone`.`Products` values(147,'Botanical Coaster 30','Botanical Coasters',4,19.95,1,'/photos/leaf30.jpg');
