-- MySQL Script generated by MySQL Workbench
-- Wed Feb 20 17:21:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clover
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clover` ;

-- -----------------------------------------------------
-- Schema clover
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clover` DEFAULT CHARACTER SET utf8 ;
USE `clover` ;

-- -----------------------------------------------------
-- Table `clover`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clover`.`Category` ;

CREATE TABLE IF NOT EXISTS `clover`.`Category` (
  `categoryID` INT NOT NULL,
  `CategoryName` VARCHAR(255) NULL,
  `Description` VARCHAR(255) NULL,
  `picture` VARCHAR(255) NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clover`.`useraccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clover`.`useraccount` ;

CREATE TABLE IF NOT EXISTS `clover`.`useraccount` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Hashpass` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `admin` TINYINT NULL,
  `FrstName` VARCHAR(255) NULL,
  `LastName` VARCHAR(255) NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clover`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clover`.`Cart` ;

CREATE TABLE IF NOT EXISTS `clover`.`Cart` (
  `UserID` INT NOT NULL,
  `CartID` INT NOT NULL AUTO_INCREMENT,
  `proudctID` INT NULL,
  `quantity` INT NULL,
  `Total` INT NULL,
  PRIMARY KEY (`CartID`, `UserID`),
  UNIQUE INDEX `idCart_UNIQUE` (`CartID` ASC),
  INDEX `UserID_idx` (`UserID` ASC),
  INDEX `productID_idx` (`proudctID` ASC),
  CONSTRAINT `productID`
    FOREIGN KEY (`proudctID`)
    REFERENCES `clover`.`Products` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `clover`.`useraccount` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clover`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clover`.`Products` ;

CREATE TABLE IF NOT EXISTS `clover`.`Products` (
  `productID` INT NOT NULL,
  `ProductName` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `categoryID` INT NULL,
  `UnitPrice` INT NULL,
  `unitsInStock` INT NULL,
  `picture` VARCHAR(255) NULL,
  `Cart_CartID` INT NOT NULL,
  PRIMARY KEY (`productID`, `Cart_CartID`),
  INDEX `categoryID_idx` (`categoryID` ASC),
  INDEX `fk_Products_Cart1_idx` (`Cart_CartID` ASC),
  CONSTRAINT `categoryID`
    FOREIGN KEY (`categoryID`)
    REFERENCES `clover`.`Category` (`categoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Cart1`
    FOREIGN KEY (`Cart_CartID`)
    REFERENCES `clover`.`Cart` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clover`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clover`.`Order` ;

CREATE TABLE IF NOT EXISTS `clover`.`Order` (
  `orderID` INT NOT NULL,
  `UserID` INT NOT NULL,
  `CartID` INT NULL,
  `Total` INT NULL,
  PRIMARY KEY (`orderID`, `UserID`),
  INDEX `fk_Order_useraccount1_idx` (`UserID` ASC),
  INDEX `fk_Order_Cart1_idx` (`CartID` ASC),
  CONSTRAINT `fk_Order_useraccount1`
    FOREIGN KEY (`UserID`)
    REFERENCES `clover`.`useraccount` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CartID`
    FOREIGN KEY (`CartID`)
    REFERENCES `clover`.`Cart` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clover`.`OrderItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clover`.`OrderItems` ;

CREATE TABLE IF NOT EXISTS `clover`.`OrderItems` (
  `Products_productID` INT NOT NULL,
  `Products_Cart_CartID` INT NOT NULL,
  `Products_Cart_CustomerID` VARCHAR(45) NOT NULL,
  `Order_orderID` INT NOT NULL,
  `Order_userID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Products_productID`, `Products_Cart_CartID`, `Products_Cart_CustomerID`, `Order_orderID`, `Order_userID`),
  INDEX `fk_Products_has_Order_Order1_idx` (`Order_orderID` ASC, `Order_userID` ASC),
  INDEX `fk_Products_has_Order_Products1_idx` (`Products_productID` ASC, `Products_Cart_CartID` ASC, `Products_Cart_CustomerID` ASC),
  CONSTRAINT `fk_Products_has_Order_Products1`
    FOREIGN KEY (`Products_productID` , `Products_Cart_CartID`)
    REFERENCES `clover`.`Products` (`productID` , `Cart_CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Order_Order1`
    FOREIGN KEY (`Order_orderID`)
    REFERENCES `clover`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
