-- MySQL Script generated by MySQL Workbench
-- Fri Mar  8 11:56:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Capstone
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Capstone` ;

-- -----------------------------------------------------
-- Schema Capstone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Capstone` DEFAULT CHARACTER SET utf8 ;
USE `Capstone` ;

-- -----------------------------------------------------
-- Table `Capstone`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Category` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Category` (
  `CategoryID` INT NOT NULL,
  `CategoryName` VARCHAR(255) NOT NULL,
  `CategoryDescription` VARCHAR(255) NOT NULL,
  `CategoryPicture` VARCHAR(255) NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Products` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Products` (
  `productID` INT NOT NULL,
  `ProductName` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `categoryID` INT NOT NULL,
  `Product_UnitPrice` INT NOT NULL,
  `unitsInStock` INT NOT NULL,
  `ProductPicture` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`productID`),
  INDEX `categoryID_idx` (`categoryID` ASC),
  CONSTRAINT `categoryID`
    FOREIGN KEY (`categoryID`)
    REFERENCES `Capstone`.`Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`useraccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`useraccount` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`useraccount` (
  `email` VARCHAR(255) NOT NULL,
  `Hashpass` VARCHAR(255) NOT NULL,
  `admin` TINYINT NOT NULL,
  `FrstName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Cart` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Cart` (
  `CartID` INT NOT NULL AUTO_INCREMENT,
  `useraccount_email` VARCHAR(255) NOT NULL,
  `quantity` INT NULL,
  `Total` INT NULL,
  PRIMARY KEY (`CartID`),
  UNIQUE INDEX `idCart_UNIQUE` (`CartID` ASC),
  INDEX `fk_Cart_useraccount1_idx` (`useraccount_email` ASC),
  CONSTRAINT `fk_Cart_useraccount1`
    FOREIGN KEY (`useraccount_email`)
    REFERENCES `Capstone`.`useraccount` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Order` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Order` (
  `orderID` INT NOT NULL,
  `CartID` INT NOT NULL,
  `Total` INT NOT NULL,
  `OrderDate` DATE NOT NULL,
  `timestamp` TIME NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_Order_Cart1_idx` (`CartID` ASC),
  UNIQUE INDEX `CartID_UNIQUE` (`CartID` ASC),
  CONSTRAINT `CartID`
    FOREIGN KEY (`CartID`)
    REFERENCES `Capstone`.`Cart` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Capstone`.`Cart_has_Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Capstone`.`Cart_has_Products` ;

CREATE TABLE IF NOT EXISTS `Capstone`.`Cart_has_Products` (
  `Cart_CartID` INT NOT NULL,
  `Cart_UserID` INT NOT NULL,
  `Products_productID` INT NOT NULL,
  `Products_Cart_CartID` INT NOT NULL,
  PRIMARY KEY (`Cart_CartID`, `Cart_UserID`, `Products_productID`, `Products_Cart_CartID`),
  INDEX `fk_Cart_has_Products_Products1_idx` (`Products_productID` ASC, `Products_Cart_CartID` ASC),
  INDEX `fk_Cart_has_Products_Cart1_idx` (`Cart_CartID` ASC, `Cart_UserID` ASC),
  CONSTRAINT `fk_Cart_has_Products_Cart1`
    FOREIGN KEY (`Cart_CartID`)
    REFERENCES `Capstone`.`Cart` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cart_has_Products_Products1`
    FOREIGN KEY (`Products_productID`)
    REFERENCES `Capstone`.`Products` (`productID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
